[package]
name = "schiebung-core"
version = "0.1.0"
edition = "2021"
keywords = ["transform", "tf", "tf2"]
categories = ["robotics"]


[dependencies]
nalgebra = "0.33.2"
petgraph = "0.7.1"
log = "0.4.25"
approx = "0.5.1"
dirs = "6.0.0"
confy = "0.6.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"