[package]
name = "schiebung-core"
version = "0.1.0"
edition = "2021"


[dependencies]

nalgebra = "*"
petgraph = "*"
iceoryx2 = "*"
schiebung-types = {path = "../schiebung-types"}
log = "*"
env_logger = "*"